// Code generated by "stringer -type=Key -trimprefix=K_ -output=key_name.go"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[K_A-4]
	_ = x[K_B-5]
	_ = x[K_C-6]
	_ = x[K_D-7]
	_ = x[K_E-8]
	_ = x[K_F-9]
	_ = x[K_G-10]
	_ = x[K_H-11]
	_ = x[K_I-12]
	_ = x[K_J-13]
	_ = x[K_K-14]
	_ = x[K_L-15]
	_ = x[K_M-16]
	_ = x[K_N-17]
	_ = x[K_O-18]
	_ = x[K_P-19]
	_ = x[K_Q-20]
	_ = x[K_R-21]
	_ = x[K_S-22]
	_ = x[K_T-23]
	_ = x[K_U-24]
	_ = x[K_V-25]
	_ = x[K_W-26]
	_ = x[K_X-27]
	_ = x[K_Y-28]
	_ = x[K_Z-29]
	_ = x[K_1-30]
	_ = x[K_2-31]
	_ = x[K_3-32]
	_ = x[K_4-33]
	_ = x[K_5-34]
	_ = x[K_6-35]
	_ = x[K_7-36]
	_ = x[K_8-37]
	_ = x[K_9-38]
	_ = x[K_0-39]
	_ = x[K_ENTER-40]
	_ = x[K_ESC-41]
	_ = x[K_BACKSPACE-42]
	_ = x[K_TAB-43]
	_ = x[K_SPACE-44]
	_ = x[K_MINUS-45]
	_ = x[K_EQUAL-46]
	_ = x[K_LEFTBRACE-47]
	_ = x[K_RIGHTBRACE-48]
	_ = x[K_BACKSLASH-49]
	_ = x[K_SEMICOLON-51]
	_ = x[K_APOSTROPHE-52]
	_ = x[K_GRAVE-53]
	_ = x[K_COMMA-54]
	_ = x[K_DOT-55]
	_ = x[K_SLASH-56]
	_ = x[K_CAPSLOCK-57]
	_ = x[K_F1-58]
	_ = x[K_F2-59]
	_ = x[K_F3-60]
	_ = x[K_F4-61]
	_ = x[K_F5-62]
	_ = x[K_F6-63]
	_ = x[K_F7-64]
	_ = x[K_F8-65]
	_ = x[K_F9-66]
	_ = x[K_F10-67]
	_ = x[K_F11-68]
	_ = x[K_F12-69]
	_ = x[K_PRINTSCREEN-70]
	_ = x[K_SCROLLLOCK-71]
	_ = x[K_PAUSE-72]
	_ = x[K_INSERT-73]
	_ = x[K_HOME-74]
	_ = x[K_PAGEUP-75]
	_ = x[K_DELETE-76]
	_ = x[K_END-77]
	_ = x[K_PAGEDOWN-78]
	_ = x[K_RIGHT-79]
	_ = x[K_LEFT-80]
	_ = x[K_DOWN-81]
	_ = x[K_UP-82]
	_ = x[K_L_CTRL-224]
	_ = x[K_L_SHIFT-225]
	_ = x[K_L_ALT-226]
	_ = x[K_L_GUI-227]
	_ = x[K_R_CTRL-228]
	_ = x[K_R_SHIFT-229]
	_ = x[K_R_ALT-230]
	_ = x[K_R_GUI-231]
}

const (
	_Key_name_0 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ENTERESCBACKSPACETABSPACEMINUSEQUALLEFTBRACERIGHTBRACEBACKSLASH"
	_Key_name_1 = "SEMICOLONAPOSTROPHEGRAVECOMMADOTSLASHCAPSLOCKF1F2F3F4F5F6F7F8F9F10F11F12PRINTSCREENSCROLLLOCKPAUSEINSERTHOMEPAGEUPDELETEENDPAGEDOWNRIGHTLEFTDOWNUP"
	_Key_name_2 = "L_CTRLL_SHIFTL_ALTL_GUIR_CTRLR_SHIFTR_ALTR_GUI"
)

var (
	_Key_index_0 = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 41, 44, 53, 56, 61, 66, 71, 80, 90, 99}
	_Key_index_1 = [...]uint8{0, 9, 19, 24, 29, 32, 37, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 66, 69, 72, 83, 93, 98, 104, 108, 114, 120, 123, 131, 136, 140, 144, 146}
	_Key_index_2 = [...]uint8{0, 6, 13, 18, 23, 29, 36, 41, 46}
)

func (i Key) String() string {
	switch {
	case 4 <= i && i <= 49:
		i -= 4
		return _Key_name_0[_Key_index_0[i]:_Key_index_0[i+1]]
	case 51 <= i && i <= 82:
		i -= 51
		return _Key_name_1[_Key_index_1[i]:_Key_index_1[i+1]]
	case 224 <= i && i <= 231:
		i -= 224
		return _Key_name_2[_Key_index_2[i]:_Key_index_2[i+1]]
	default:
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
